import 'package:flutter/material.dart';
import 'package:provider/provider.dart';
import '../../../core/api/api_service.dart';
import '../../../core/providers/gym_branding_provider.dart';
import '../../../core/localization/app_strings.dart';

/// Dialog for creating a new staff member.
///
/// Shows a form with fields for name, username, email, password, phone,
/// role, and branch. On submit, calls POST /api/users.
class AddStaffDialog extends StatefulWidget {
  final ApiService apiService;
  final VoidCallback onStaffCreated;

  const AddStaffDialog({
    super.key,
    required this.apiService,
    required this.onStaffCreated,
  });

  @override
  State<AddStaffDialog> createState() => _AddStaffDialogState();
}

class _AddStaffDialogState extends State<AddStaffDialog> {
  final _formKey = GlobalKey<FormState>();
  final _fullNameController = TextEditingController();
  final _usernameController = TextEditingController();
  final _emailController = TextEditingController();
  final _passwordController = TextEditingController();
  final _phoneController = TextEditingController();

  String _selectedRole = 'front_desk';
  int? _selectedBranchId;
  List<Map<String, dynamic>> _branches = [];
  bool _isLoading = false;
  bool _loadingBranches = true;
  String _emailDomain = 'gym.com';
  bool _emailAutoGenerated = true; // track if user edited email manually

  static const _roles = [
    {'value': 'branch_manager', 'label': S.branchManager, 'icon': Icons.manage_accounts, 'needsBranch': true},
    {'value': 'front_desk', 'label': S.frontDesk, 'icon': Icons.support_agent, 'needsBranch': true},
    {'value': 'branch_accountant', 'label': S.branchAccountant, 'icon': Icons.account_balance, 'needsBranch': true},
    {'value': 'central_accountant', 'label': S.centralAccountant, 'icon': Icons.account_balance_wallet, 'needsBranch': false},
  ];

  bool get _needsBranch {
    final role = _roles.firstWhere((r) => r['value'] == _selectedRole, orElse: () => _roles.first);
    return role['needsBranch'] as bool;
  }

  @override
  void initState() {
    super.initState();
    _loadBranches();
    // Auto-generate email when username changes
    _usernameController.addListener(_autoGenerateEmail);
    // Get gym email domain from branding
    WidgetsBinding.instance.addPostFrameCallback((_) {
      final branding = context.read<GymBrandingProvider>();
      setState(() {
        _emailDomain = branding.emailDomain;
      });
    });
  }

  void _autoGenerateEmail() {
    if (!_emailAutoGenerated) return;
    final username = _usernameController.text.trim().toLowerCase();
    if (username.isNotEmpty) {
      _emailController.text = '$username@$_emailDomain';
    } else {
      _emailController.text = '';
    }
  }

  @override
  void dispose() {
    _fullNameController.dispose();
    _usernameController.dispose();
    _emailController.dispose();
    _passwordController.dispose();
    _phoneController.dispose();
    super.dispose();
  }

  Future<void> _loadBranches() async {
    try {
      final response = await widget.apiService.get('/api/branches');
      if (response.statusCode == 200 && response.data != null) {
        List<dynamic> rawList = [];
        final d = response.data;
        if (d is List) {
          rawList = d;
        } else if (d['data'] is List) {
          rawList = d['data'];
        } else if (d['data'] is Map && d['data']['items'] is List) {
          rawList = d['data']['items'];
        } else if (d['branches'] is List) {
          rawList = d['branches'];
        }
        setState(() {
          _branches = rawList.map((b) => {
            'id': b['id'] as int,
            'name': (b['name'] ?? 'Branch ${b['id']}') as String,
          }).toList();
          if (_branches.isNotEmpty) {
            _selectedBranchId = _branches.first['id'] as int;
          }
          _loadingBranches = false;
        });
      }
    } catch (e) {
      debugPrint('Error loading branches: $e');
      setState(() => _loadingBranches = false);
    }
  }

  Future<void> _submit() async {
    if (!_formKey.currentState!.validate()) return;

    setState(() => _isLoading = true);

    try {
      final data = <String, dynamic>{
        'full_name': _fullNameController.text.trim(),
        'username': _usernameController.text.trim(),
        'email': _emailController.text.trim(),
        'password': _passwordController.text,
        'role': _selectedRole,
      };

      if (_phoneController.text.trim().isNotEmpty) {
        data['phone'] = _phoneController.text.trim();
      }

      if (_needsBranch && _selectedBranchId != null) {
        data['branch_id'] = _selectedBranchId;
      }

      await widget.apiService.post('/api/users', data: data);

      if (mounted) {
        Navigator.of(context).pop();
        ScaffoldMessenger.of(context).showSnackBar(
          SnackBar(
            content: Text(S.staffAddedSuccess(_fullNameController.text.trim())),
            backgroundColor: Colors.green,
          ),
        );
        widget.onStaffCreated();
      }
    } catch (e) {
      if (mounted) {
        final msg = e.toString().replaceAll('Exception: ', '');
        ScaffoldMessenger.of(context).showSnackBar(
          SnackBar(content: Text('Error: $msg'), backgroundColor: Colors.red),
        );
      }
    } finally {
      if (mounted) setState(() => _isLoading = false);
    }
  }

  @override
  Widget build(BuildContext context) {
    return Dialog(
      insetPadding: const EdgeInsets.symmetric(horizontal: 16, vertical: 24),
      shape: RoundedRectangleBorder(borderRadius: BorderRadius.circular(20)),
      child: ConstrainedBox(
        constraints: const BoxConstraints(maxWidth: 500),
        child: Padding(
          padding: const EdgeInsets.all(24),
          child: Form(
            key: _formKey,
            child: SingleChildScrollView(
              child: Column(
                mainAxisSize: MainAxisSize.min,
                crossAxisAlignment: CrossAxisAlignment.stretch,
                children: [
                  // Header
                  Row(
                    children: [
                      const Icon(Icons.person_add, size: 28),
                      const SizedBox(width: 12),
                      Expanded(
                        child: Text(
                          S.addNewStaff,
                          style: Theme.of(context).textTheme.titleLarge?.copyWith(
                                fontWeight: FontWeight.bold,
                              ),
                        ),
                      ),
                      IconButton(
                        onPressed: () => Navigator.of(context).pop(),
                        icon: const Icon(Icons.close),
                      ),
                    ],
                  ),
                  const Divider(height: 24),

                  // Full Name
                  TextFormField(
                    controller: _fullNameController,
                    decoration: const InputDecoration(
                      labelText: S.fullNameRequired,
                      prefixIcon: Icon(Icons.person),
                      hintText: S.fullNameHint,
                    ),
                    textCapitalization: TextCapitalization.words,
                    validator: (v) => (v == null || v.trim().isEmpty) ? S.required : null,
                  ),
                  const SizedBox(height: 12),

                  // Username
                  TextFormField(
                    controller: _usernameController,
                    decoration: const InputDecoration(
                      labelText: S.usernameRequired2,
                      prefixIcon: Icon(Icons.alternate_email),
                      hintText: S.usernameHint,
                    ),
                    validator: (v) {
                      if (v == null || v.trim().isEmpty) return S.required;
                      if (v.trim().length < 3) return S.atLeast3Chars;
                      return null;
                    },
                  ),
                  const SizedBox(height: 12),

                  // Email (auto-generated from username@gymname)
                  TextFormField(
                    controller: _emailController,
                    decoration: InputDecoration(
                      labelText: S.emailRequired,
                      prefixIcon: const Icon(Icons.email),
                      hintText: S.autoGeneratedFromUsername,
                      suffixIcon: _emailAutoGenerated
                          ? Tooltip(
                              message: S.autoGeneratedFromUsername,
                              child: Icon(Icons.auto_fix_high, color: Colors.green[400], size: 20),
                            )
                          : IconButton(
                              icon: const Icon(Icons.refresh, size: 20),
                              tooltip: S.resetToAutoGenerated,
                              onPressed: () {
                                setState(() => _emailAutoGenerated = true);
                                _autoGenerateEmail();
                              },
                            ),
                    ),
                    keyboardType: TextInputType.emailAddress,
                    onChanged: (v) {
                      // If user manually edits, stop auto-generation
                      final expected = '${_usernameController.text.trim().toLowerCase()}@$_emailDomain';
                      if (v != expected) {
                        _emailAutoGenerated = false;
                      }
                    },
                    validator: (v) {
                      if (v == null || v.trim().isEmpty) return S.required;
                      if (!v.contains('@')) return S.invalidEmail;
                      return null;
                    },
                  ),
                  const SizedBox(height: 12),

                  // Password
                  TextFormField(
                    controller: _passwordController,
                    decoration: const InputDecoration(
                      labelText: S.passwordRequired2,
                      prefixIcon: Icon(Icons.lock),
                      hintText: S.min6Chars,
                    ),
                    obscureText: true,
                    validator: (v) {
                      if (v == null || v.isEmpty) return S.required;
                      if (v.length < 6) return S.atLeast6Chars;
                      return null;
                    },
                  ),
                  const SizedBox(height: 12),

                  // Phone (optional)
                  TextFormField(
                    controller: _phoneController,
                    decoration: const InputDecoration(
                      labelText: S.phoneOptional,
                      prefixIcon: Icon(Icons.phone),
                    ),
                    keyboardType: TextInputType.phone,
                  ),
                  const SizedBox(height: 16),

                  // Role selector
                  Text(S.roleRequired, style: Theme.of(context).textTheme.titleSmall),
                  const SizedBox(height: 8),
                  Wrap(
                    spacing: 8,
                    runSpacing: 8,
                    children: _roles.map((role) {
                      final isSelected = _selectedRole == role['value'];
                      return ChoiceChip(
                        label: Row(
                          mainAxisSize: MainAxisSize.min,
                          children: [
                            Icon(role['icon'] as IconData, size: 16),
                            const SizedBox(width: 4),
                            Text(role['label'] as String),
                          ],
                        ),
                        selected: isSelected,
                        onSelected: (_) => setState(() {
                          _selectedRole = role['value'] as String;
                        }),
                        selectedColor: Theme.of(context).colorScheme.primary.withOpacity(0.2),
                      );
                    }).toList(),
                  ),
                  const SizedBox(height: 16),

                  // Branch selector (only for branch-specific roles)
                  if (_needsBranch) ...[
                    Text(S.branchRequired, style: Theme.of(context).textTheme.titleSmall),
                    const SizedBox(height: 8),
                    if (_loadingBranches)
                      const Center(child: CircularProgressIndicator())
                    else if (_branches.isEmpty)
                      Container(
                        padding: const EdgeInsets.all(12),
                        decoration: BoxDecoration(
                          color: Colors.orange.withOpacity(0.1),
                          borderRadius: BorderRadius.circular(8),
                        ),
                        child: const Text(S.noBranchesCreateFirst),
                      )
                    else
                      DropdownButtonFormField<int>(
                        value: _selectedBranchId,
                        items: _branches.map((b) {
                          return DropdownMenuItem<int>(
                            value: b['id'] as int,
                            child: Text(b['name'] as String),
                          );
                        }).toList(),
                        onChanged: (v) => setState(() => _selectedBranchId = v),
                        decoration: const InputDecoration(
                          prefixIcon: Icon(Icons.store),
                          border: OutlineInputBorder(),
                        ),
                        validator: (v) => v == null ? S.selectBranch : null,
                      ),
                    const SizedBox(height: 16),
                  ],

                  // Submit button
                  const SizedBox(height: 8),
                  ElevatedButton.icon(
                    onPressed: _isLoading ? null : _submit,
                    icon: _isLoading
                        ? const SizedBox(
                            width: 18,
                            height: 18,
                            child: CircularProgressIndicator(strokeWidth: 2),
                          )
                        : const Icon(Icons.check),
                    label: Text(_isLoading ? S.creating : S.createStaffMember),
                    style: ElevatedButton.styleFrom(
                      padding: const EdgeInsets.symmetric(vertical: 14),
                      shape: RoundedRectangleBorder(borderRadius: BorderRadius.circular(12)),
                    ),
                  ),
                ],
              ),
            ),
          ),
        ),
      ),
    );
  }
}
